version: '3.2'
services:
  fastapi:
    build: 
      dockerfile: FastAPI/Dockerfile
      context: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --proxy-headers
  flutter:
    image: app_interface
    build:
      dockerfile: app_interface/Dockerfile
      context: .
    depends_on:
      - emulator Install
    ports:
      - "4200:80"
    volumes:
      - './:./app_interface'
  neo4j:
      image: neo4j:latest
      build:
        context: .
        dockerfile: neo4j/Dockerfile
      container_name: neo4j
      environment:
        - NEO4J_AUTH=neo4j/test  # username: neo4j, password: test
      ports:
        - "7474:7474"  # HTTP access
        - "7687:7687"  # Bolt access
      volumes:
        - neo4j_data:/data
        - neo4j_logs:/logs
        - neo4j_import:/var/lib/neo4j/import
        - neo4j_plugins:/plugins
  
  fast:
     container_name: fast
     expose:
        - 8000
     networks:
       - my_network
    
     ports:
        - 8000:8000
     restart: unless-stopped
     build:
      context: .
      dockerfile: Dockerfile
      
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  my_network:
    driver: bridge