version: '3.8'

services:
  flutter:
    build:
      context: ./app_interface
      dockerfile: Dockerfile
    ports:
      - "1200:80"
    volumes:
      - './run/desktop/mnt/host/c/Users/davidantoine/readaptic/app_interface:/app_interface:rw'

  neo4j:
    image: neo4j:5.13.0
    container_name: 'neo4j'
    volumes:
      - ./docker.sh:/docker-entrypoint-initdb.d/docker.sh
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PLUGINS=["apoc"]
    restart: on-failure
    networks:
        - my_network
    command: neo4j

  fastapi:
    container_name: fastapi
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

volumes:
  fastapi_data:
  dgraph:

networks:
  my_network:
    driver: bridge
