version: '3.8'

services:
  flutter:
    build:
      context: ./app_interface
      dockerfile: Dockerfile
    ports:
      - "1200:1200"
    volumes:
      - './run/desktop/mnt/host/c/Users/davidantoine/readaptic/app_interface:/app_interface:rw'

  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/conf/:/conf/'
      - '$HOME/neo4j/plugins:/plugins'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PLUGINS=["apoc"]
    restart: on-failure
    networks:
        - my_network
    command: neo4j

  fastapi:
    container_name: fastapi
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  fastapi_data:
  dgraph:

networks:
  my_network:
    driver: bridge
